### PR TITLE
Installing node-red-node-group dependency & Fixed Marker for States

### PR DESCRIPTION
**Pull request by mridulrb**

### CODE REVIEW

**Comment by johnwalicki** [comment]
@mridulrb Thanks for the suggested patches. I am going to reject this patch because while the developer could install node-red-node-group, I really want them to install Node-RED v1.1.  There are other subtle requirements.

Also the Marker code is working correctly in the original flow.  It gets the lat/lng from the TWC location call.

**Comment by johnwalicki** [comment]
closing PR

**Comment by mridulrb** [comment]
@johnwalicki No problem, I faced this issues while running Node-RED locally and I applied this patches which worked.

**Comment by johnwalicki** [comment]
The TWC disease tracker API does indeed return the lat/lng but its unreliable.  I opened a bug report with TWC engineering. I used the TWC Location search API instead.

**Pull request closed without merging**
